<div class="content">
    <h2 class="table-name">Table name</h2>
    <table class="admin-table">
        <tr>
            <td>
                id товара
            </td>
            <td>
                title
            </td>
            <td>
                decription
            </td>
            <td>
                foto
            </td>
            <td>
                another
            </td>
        </tr>
        <tr>
            <td>
                id товара
            </td>
            <td>
                title
            </td>
            <td>
                decription
            </td>
            <td>
                foto
            </td>
            <td>
                another
            </td>
        </tr>

        <tr>
            <td>
                id товара
            </td>
            <td>
                title
            </td>
            <td>
                decription
            </td>
            <td>
                foto
            </td>
            <td>
                another
            </td>
        </tr>
        <tr>
            <td>
                id товара
            </td>
            <td>
                title
            </td>
            <td>
                decription
            </td>
            <td>
                foto
            </td>
            <td>
                another
            </td>
        </tr>
        <tr>
            <td>
                id товара
            </td>
            <td>
                title
            </td>
            <td>
                decription
            </td>
            <td>
                foto
            </td>
            <td>
                another
            </td>
        </tr>

        <tr>
            <td>
                id товара
            </td>
            <td>
                title
            </td>
            <td>
                decription
            </td>
            <td>
                foto
            </td>
            <td>
                another
            </td>
        </tr>
        <tr>
            <td>
                id товара
            </td>
            <td>
                title
            </td>
            <td>
                decription
            </td>
            <td>
                foto
            </td>
            <td>
                another
            </td>
        </tr>
        <tr>
            <td>
                id товара
            </td>
            <td>
                title
            </td>
            <td>
                decription
            </td>
            <td>
                foto
            </td>
            <td>
                another
            </td>
        </tr>
        <tr>
            <td>
                id товара
            </td>
            <td>
                title
            </td>
            <td>
                decription
            </td>
            <td>
                foto
            </td>
            <td>
                another
            </td>
        </tr>
        <tr>
            <td>
                id товара
            </td>
            <td>
                title
            </td>
            <td>
                decription
            </td>
            <td>
                foto
            </td>
            <td>
                another
            </td>
        </tr>

        <tr>
            <td>
                id товара
            </td>
            <td>
                title
            </td>
            <td>
                decription
            </td>
            <td>
                foto
            </td>
            <td>
                another
            </td>
        </tr>
        <tr>
            <td>
                id товара
            </td>
            <td>
                title
            </td>
            <td>
                decription
            </td>
            <td>
                foto
            </td>
            <td>
                another
            </td>
        </tr>

        <tr>
            <td>
                id товара
            </td>
            <td>
                title
            </td>
            <td>
                decription
            </td>
            <td>
                foto
            </td>
            <td>
                another
            </td>
        </tr>
        <tr>
            <td>
                id товара
            </td>
            <td>
                title
            </td>
            <td>
                decription
            </td>
            <td>
                foto
            </td>
            <td>
                another
            </td>
        </tr>

        <tr>
            <td>
                id товара
            </td>
            <td>
                title
            </td>
            <td>
                decription
            </td>
            <td>
                foto
            </td>
            <td>
                another
            </td>
        </tr>
        <tr>
            <td>
                id товара
            </td>
            <td>
                title
            </td>
            <td>
                decription
            </td>
            <td>
                foto
            </td>
            <td>
                another
            </td>
        </tr>
        <tr>
            <td>
                id товара
            </td>
            <td>
                title
            </td>
            <td>
                decription
            </td>
            <td>
                foto
            </td>
            <td>
                another
            </td>
        </tr>
        <tr>
            <td>
                id товара
            </td>
            <td>
                title
            </td>
            <td>
                decription
            </td>
            <td>
                foto
            </td>
            <td>
                another
            </td>
        </tr>
    </table>
    <a href="#">показать ещё 50 товаров >></a>
    <span class="table-text">Общее количество - 1546 товаров</span>
    <span class="table-text">Товаров на сумму - 23456789 грн. </span>
</div>